### ISSUE TITLE
There are three questions I need to ask.

### ISSUE THREAD

**Issue by tarimren-admin** [SmileYzn/AccuracyFix#10]
1. After enabling the AccuracyFix module with default parameters, the Desert Eagle's accuracy is very high, completely different from the default feeling in Steam.
2. What is the specific function of The default aim distance check of an weapon and The default distance to fix trace line， What is the impact of parameter values 4096 and 8192?

**Comment by SmileYzn** [comment]
1. It is a question?
2. It's units max distance that trace line consider to specify that line is aiming any part of body of an player. 4096 is huge distance. Even some maps do not have that space! 8192 is maximum of units that hl engine can have in a map size if I remember correctly. You can put values down until get acceptable results. That values are fixed because of map distances like dust. So you can adjust every weapon distances for rifles, pistols, sub machines and others.

That plugin does is fix that line to correct bod part that you aiming. And adjust ridiculous trace line of original hl engine.

To be honest USP and deagle are overpowered with this fix. Maybe need to adjust better to other weapons changing something in traveling that o do not know 🤦‍♂️

**Comment by SmileYzn** [comment]
@tarimren-admin 
That make sense for you?
